version: "2"

services:
    php:
        container_name: icrc-php
        build:
            context: .
            dockerfile: .docker/icrc-php/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 9000
        depends_on:
            - db


    db:
        container_name: icrc-db
        image: mysql:latest
        volumes:
            - "./.docker/mysql:/var/lib/mysql"
            - "./.docker/db/:/docker-entrypoint-initdb.d/"
        ports:
            - 3307:3306
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=icrc_db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root

    nginx:
        container_name: icrc-nginx
        image: nginx:latest
        hostname: "icrc.dev"
        links:
            - php
        ports: 
            - 8000:80
        volumes:
            - .docker/icrc-nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
 
